config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  resources :hotelgroups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	belongs_to :hotelgroup
end

app/models/hotelgroup.rb
class Hotelgroup < ApplicationRecord
	has_many :hotels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotelgroups_controller.rb
class HotelgroupsController < ApplicationController
before_action :current_hotelgroup, only: [:show, :edit, :update, :destroy]

	def index
    @hotelgroups = Hotelgroup.all
  end

  def show

  end

  def new
    @hotelgroup = Hotelgroup.new
  end

  def create
    hotelgroup = Hotelgroup.create(hotelgroup_params)

    redirect_to hotelgroup_path(hotelgroup)
  end

  def edit

  end

  def update
    @hotelgroup.update(hotelgroup_params)

    redirect_to hotelgroup_path(@hotelgroup)
  end

  def destroy
    @hotelgroup.destroy

    redirect_to hotelgroups_path
  end

  private

  def hotelgroup_params
    params.require(:hotelgroup).permit(:name)
  end

  def current_hotelgroup
    @hotelgroup = Hotelgroup.find(params[:id])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

before_action :current_hotel, only: [:show, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def show

  end

  def new
    @hotel = Hotel.new
  end

  def create
    hotel = Hotel.create(hotel_params)

    redirect_to hotel_path(hotel)
  end

  def edit

  end

  def update
    @hotel.update(hotel_params)

    redirect_to hotel_path(@hotel)
  end

  def destroy
    @hotel.destroy

    redirect_to hotels_path
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name)
  end

  def current_hotel
    @hotel = Hotel.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotelgroups_helper.rb
module HotelgroupsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotelgroups/edit.html.erb
<h3>Update HotelGroup Details</h3>
<%= form_with model: @hotelgroup do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.submit %>
<% end %>

app/views/hotelgroups/index.html.erb
<table>
  <% @hotelgroups.each do |hotelgroup| %>
    <tr>
      <td><%= link_to hotelgroup.name, hotelgroup_path(hotelgroup) %></td>
      <td><%= button_to 'Edit', edit_hotelgroup_path(hotelgroup), method: 'get'%></td>
      <td><%= button_to 'Remove', hotelgroup_path(hotel), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Hotelgroup", new_hotelgroup_path %>

app/views/hotelgroups/new.html.erb
<h3>Create a HotelGroup</h3>
<%= form_with model: @hotelgroup do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.submit %>
<% end %>

app/views/hotelgroups/show.html.erb
<h1><%= @hotelgroup.name %></h1>
<%= link_to 'Remove', @hotelgroup, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/hotels/edit.html.erb
<h3>Update Hotel Details</h3>
<%= form_with model: @hotel do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.submit %>
<% end %>

app/views/hotels/index.html.erb
<table>
  <% @hotels.each do |hotel| %>
    <tr>
      <td><%= link_to hotel.name, hotel_path(hotel) %></td>
      <td><%= button_to 'Edit', edit_hotel_path(hotel), method: 'get'%></td>
      <td><%= button_to 'Remove', hotel_path(hotel), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h3>Create a Hotel</h3>
<%= form_with model: @hotel do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.submit %>
<% end %>

<!-- <%= form_for @hotel do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.submit %>
<% end %> -->

app/views/hotels/show.html.erb
<h1><%= @hotel.name %></h1>
<%= link_to 'Remove', @hotel, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelNatraj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>